services:
  dyad-web:
    container_name: dyad-web
    profiles:
      - dev
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    environment:
      NODE_ENV: development

    command: ["npx","vite","--config","vite.renderer.config.mts","--host","0.0.0.0","--port","5173"]
  dyad-prod:
    container_name: dyad-prod
    profiles:
      - prod
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
    environment:
      NODE_ENV: production
    ports:
      - "${DYAD_PROD_PORT:-8080}:80"
