version: '3.8'

services:
  dyad-dev:
    profiles: ["dev"]
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    ports:
      - "${DYAD_WEB_PORT:-5173}:5173"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.pnpm-store
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true

  dyad-prod:
    profiles: ["prod"]
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "${DYAD_PROD_PORT:-8080}:80"
    environment:
      - NODE_ENV=production
