version: '3.8'

services:
  dyad-dev:
    profiles: ["dev"]
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${DYAD_WEB_PORT:-5173}:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
    command: npm run dev

  dyad-prod:
    profiles: ["prod"]
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "${DYAD_PROD_PORT:-8080}:80"
    environment:
      - NODE_ENV=production
