FROM node:20-bullseye
WORKDIR /app
RUN apt-get update && apt-get install -y python3 build-essential && rm -rf /var/lib/apt/lists/*
COPY package*.json ./
RUN npm ci
COPY . .
EXPOSE 5173
CMD ["npx","vite","--config","vite.renderer.config.mts","--host","0.0.0.0","--port","5173"]
